"""Second attempt at adding panels

Revision ID: c3bc8693ca34
Revises: 226c6ce128c8
Create Date: 2026-06-15 19:26:43.210495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3bc8693ca34'
down_revision: Union[str, Sequence[str], None] = '226c6ce128c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('panel_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('service_url', sa.String(), nullable=False),
    sa.Column('frontend_endpoint', sa.String(), nullable=False),
    sa.Column('frontend_checksum', sa.String(), nullable=False),
    sa.Column('api_base', sa.String(), nullable=False),
    sa.Column('publishes', sa.JSON(), nullable=True),
    sa.Column('subscribes', sa.JSON(), nullable=True),
    sa.Column('focus_components', sa.JSON(), nullable=True),
    sa.Column('required_role', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panels')
    # ### end Alembic commands ###
