"""add_required_role_to_panels

Revision ID: a20222f28e19
Revises: 4d06a99cb2f9
Create Date: 2026-06-10 15:39:08.622607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20222f28e19'
down_revision: Union[str, Sequence[str], None] = '4d06a99cb2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_registrations', sa.Column('required_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panel_registrations', 'required_role')
    # ### end Alembic commands ###
