"""add services drop panels

Revision ID: c17917c28521
Revises: a20222f28e19
Create Date: 2026-06-15 17:59:00.140406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c17917c28521'
down_revision: Union[str, Sequence[str], None] = 'a20222f28e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('service_token', sa.String(), nullable=False),
    sa.Column('service_url', sa.String(), nullable=False),
    sa.Column('health_endpoint', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id'),
    sa.UniqueConstraint('service_token')
    )
    op.drop_table('user_layouts')
    op.drop_table('panel_registrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_registrations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('panel_id', sa.VARCHAR(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(), nullable=False),
    sa.Column('version', sa.VARCHAR(), nullable=False),
    sa.Column('service_url', sa.VARCHAR(), nullable=False),
    sa.Column('health_endpoint', sa.VARCHAR(), nullable=False),
    sa.Column('frontend_endpoint', sa.VARCHAR(), nullable=False),
    sa.Column('frontend_checksum', sa.VARCHAR(), nullable=False),
    sa.Column('api_base', sa.VARCHAR(), nullable=False),
    sa.Column('publishes', sqlite.JSON(), nullable=True),
    sa.Column('subscribes', sqlite.JSON(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('registered_at', sa.DATETIME(), nullable=True),
    sa.Column('last_verified_at', sa.DATETIME(), nullable=True),
    sa.Column('focus_components', sqlite.JSON(), nullable=True),
    sa.Column('required_role', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id')
    )
    op.create_table('user_layouts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('layout', sqlite.JSON(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('services')
    # ### end Alembic commands ###
